/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FunnelRouteImport } from './routes/funnel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FunnelThankyouRouteImport } from './routes/funnel.thankyou'

const FunnelRoute = FunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelThankyouRoute = FunnelThankyouRouteImport.update({
  id: '/thankyou',
  path: '/thankyou',
  getParentRoute: () => FunnelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/funnel': typeof FunnelRouteWithChildren
  '/funnel/thankyou': typeof FunnelThankyouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/funnel': typeof FunnelRouteWithChildren
  '/funnel/thankyou': typeof FunnelThankyouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/funnel': typeof FunnelRouteWithChildren
  '/funnel/thankyou': typeof FunnelThankyouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/funnel' | '/funnel/thankyou'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/funnel' | '/funnel/thankyou'
  id: '__root__' | '/' | '/funnel' | '/funnel/thankyou'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FunnelRoute: typeof FunnelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/funnel': {
      id: '/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnel/thankyou': {
      id: '/funnel/thankyou'
      path: '/thankyou'
      fullPath: '/funnel/thankyou'
      preLoaderRoute: typeof FunnelThankyouRouteImport
      parentRoute: typeof FunnelRoute
    }
  }
}

interface FunnelRouteChildren {
  FunnelThankyouRoute: typeof FunnelThankyouRoute
}

const FunnelRouteChildren: FunnelRouteChildren = {
  FunnelThankyouRoute: FunnelThankyouRoute,
}

const FunnelRouteWithChildren =
  FunnelRoute._addFileChildren(FunnelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FunnelRoute: FunnelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
